# Generated by Django 2.2.11 on 2020-06-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200617_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(null=True, upload_to='images/Apartment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='service.ProjectType'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/Service'),
        ),
    ]
