# Generated by Django 2.2.11 on 2020-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200617_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(upload_to='images/Apartment'),
        ),
    ]
