# Generated by Django 2.2.11 on 2020-06-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200617_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temoignage',
            name='auteur',
        ),
        migrations.AddField(
            model_name='temoignage',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/Temoignage'),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
